spring.application.name=gastos

# Conexión a MariaDB
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/control_gastos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8080